//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruSignBackEnd.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Points
    {
        public Nullable<bool> isempty { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<long> when { get; set; }
        public Nullable<long> SignatureId { get; set; }
        public long id { get; set; }
    }
}
