// <auto-generated />
namespace PruSignBackEnd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Deviceaddedforsignatures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Deviceaddedforsignatures));
        
        string IMigrationMetadata.Id
        {
            get { return "201801051440057_Device added for signatures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
